extends Node

var list : Array = [
	# Editions/Versions
	"Collector's Collector's Edition",
	"Game of the Year, Every Year Edition",
	"What The HELL Is This Version",
	"idk we forgor what version this is Version",
	"\"Dude, It's Like Dark Souls!\" Edition",
	"Rushed To Stores Because Our Bank Accounts' In The Red Edition",
	"Money Laundering Edition",
	"I Am In Dire Need Of Money Edition",
	"Version Where Each Frame Makes A Good Wallpaper For Your Desktop",
	"Rainbow Madness Edition (What, Ya Don't Like My Rainbows?)",
	"Is The Exact Same Game Except Charlie Is Even Gayer Edition",
	"Likely To Be Full Of Carefully Curated Misinformation Edition",
	"Actually An Older Version But We Marketed It To Be The Latest Version Version",
	"Premium Edition + Plus Expansion Pack (You Paid 50 Dollars For NOTHING)",
	"Frontpaged, Yet Delisted Version",
	"CENSORED By WOKE MEDIA Editon",
	"WOKE and GAY and LIBERAL Edition",
	"Rainbow Propaganda Edition",
	"Orient Express Edition",
	"American Century of Humiliation Edition",
	"Going Woke, Gone Broke Edition (We Are In Desperate Need Of Your Money)",
	"DIDN'T Go Woke, DIDN'T Go Broke Edition! (I Am Now Extremely Self-Repressed)",
	"Version Meant To Convert Your Sons Into Anarcho-Communist Gay Femboys Version",
	"Version That Injects Estrogen Into Your Body Edition (Yes It Can Do That)",
	"Radically LGBTQ+ Supportive Edition",
	"Poorly Compiled From GitHub Edition (12th Attempt)",
	"If Else If Else If Else Edition",
	"The Version That Banned Midgetsausage From Itch.io",
	"The Version That Banned Midgetsausage From Newgrounds",
	"Competitively Racist Edition",
	"Competitively Misogynist Edition",
	"Comes Free With All of COOPER BULLET Edition",
	"This Version Is Not Political (This Is Not A Political Message)",
	"Most Likely To Get A DMCA Version",
	"Nightsoil Edition",
	"Farcical Aquatic Ceremony Edition",
	"Version That Hangs Onto Outdated Imperialist Dogma, Which Perpetuates The Economic and Social Differences In Our Society",
	"Version That Perpetuates Global Inequalities, And Reinforces Power Imbalances Between Developed And Developing Countries",
	"Most Likely To Get Multiple DMCAs Version",
	"DMCA-Ridden Version",
	"Tourist Edition (Anything You Do Will Be Met With Harsh Criticism From Nerds)",
	"Maintained By A Janitor and A Potted Plant Edition",
	"Lame Pirated SteamUnlocked.net Version",
	"Lame Pirated Softonic.com Version",
	"Lame Getonpc.com Version",
	"Pop Danthology 20-something Mix",
	"Christian Pandering Edition",
	"Video Essay Edition",
	"Comprised of 95% Community Fixes Edition",
	"Poorly Researched Video Essay Edition",
	"Dangerously Poorly Researched Video Essay Edition",
	"You Will Be Threatened To Tell Your Friends To Wishlist AWoT Edition",
	"This Version Makes Fun Of Your Childhood Trauma",
	"This Version Makes Fun Of Your Insecurities",
	"Torrented By A Bunch Of Stupid F###ing Leechers Edition",
	"Zero Playtesting Edition (We Don't Know If It Even Runs!)",
	"Dozens Of Memory Leaks Everywhere You Look Edition",
	"Profanity-Laden Codebase Edition",
	"Totally Not Pirated Version",
	"F--- You Idiot Give Us All Your Money Collection",
	"Free-2-Play Version (Get AWOT Premium Now! awasteotime.com/getpremium.php)",
	"Whoever Owns This Version Is An Idiot Edition",
	"Expired Steam Summer Sale Edition",
	"Expired Steam Winter Sale Edition",
	"Can Run Anywhere! (Yes, Anywhere!) Edition",
	"Made Primarily With Godot Asset Library Stuff Edition",
	"A WOKE of Time Edition",
	"Likely To Piss PETA Off Version",
	"Rejected By The ESRB For Unknown Reasons Edition",
	"Rejected By Unknown Newgrounds Mods For Equally Unknown Reasons Edition",
	"Rejected By Valve For Unknown Reasons Edition",
	"[REDACTED] Edition: Now With [REDACTED]!",
	"Italian Spaghetti Code Version",
	"Alfred Hitchcock-Inspired Edition",
	"This Version Comes Prepackaged With IGOR By Tyler, The Creator",
	"This Version Comes Prepackaged With CHROMAKOPIA by Tyler, The Creator",
	"20th Anniversary Edition (Or Would Be If We Shipped This Off Earlier)",
	"The Version That Tipped Midgetsausage Off To Filipino Authorities Version",
	"Delay Lama Soundtrack Edition",
	'DRM-Embedded "Emulation Is Bad and So Is Gay Marriage" Edition',
	"Optimized For Game Journos Version",
	"Restricted Steam Workshop Compatibility Edition",
	"Lotsa Versions Compiled Into One Version Because Game Dev Is Hard Version",
	"'Yeah, We're Absolutely Gay As Hell' Version",
	"EU-Blacklisted Edition",
	"Extended Car Warranty Edition",
	"Flower Boy Edition",
	"Flower Girl Edition",
	"Illegal Ko-Fi Leak Edition",
	"RIOT! Edition",
	"Dadurdur Edition (Size XXL)",
	"Saul Bass Tribute Edition",
	"Overcompressed Soundtrack Edition (Midgetsausage Does Not Know How To Master)",
	"Undercompressed Soundtrack Edition (Midgetsausage Does Not Know How To Master)",
	"Used For Hacking Into People's Discord Accounts Edition",
	"We Forgot What Version This Is But Let's Hope It's The Current Version",
	"Absolute Time Waster Edition",
	"128GB Western Game Edition (This Is The Only Game We Want You To Play)",
	"Advertisement-Riddled Edition",
	"I Am Insecure Version (Like, I Have Many Security Vulnerabilities)",
	"I Am Insecure Version (Like, Mentally)",
	"I Am Unsure of My Position In Society Edition",
	"I Do Not Talk To Women Edition (Not Even Charlie, From A Waste o' Time)",
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA Edition",
	"Charlie.EXE Edition",
	"Little Monsters Edition",
	"Tells You To Smell Exhaust Edition (Go Ahead, Smell Your Exhaust Pipes)",
	"Tells You To Throw Your Old Car Batteries Into The Ocean Edition",
	"Version For Cucks Everywhere!",
	"Mori Calliope-Sponsored Version",
	"You're Growing Old and You Will Watch Everyone You Love Die Edition",
	"Modded GameBanana Femboy Charlie (+18!!! +18) Edition",
	"Version But With Dubious Mods Preinstalled For Whatever Reason",
	"Vocaloid Soundtrack Edition",
	"Call Me When You Get Lost Edition",
	"Oh God Why The Hell Does This Game Take A Long Time To Load Edition",
	"Pre-Pre-Alpha Edition (Like, A Version Before It Even Existed)",
	"The Version You Buy, But You'll Never Own",
	"The Version You Own, But You'll Never Buy (???)", # whuh?????
	"Estrogen Alternative Version",
	"Will Make You Fight With Random Sweaty Nerds Online At 2 In The Morning Edition",
	"Version Edition Version Edition Version Edition Version Edition",
	"Testosterone Alternative Version",
	"Just An Ordinary Version of AWoT But It Knows When Exactly You'll Die",
	"We Know When You Die Edition",
	"Live and Let Die Edition",
	"Good Kid, m.A.A.d. Edition",
	"You're Never Getting This Version",
	"Version That's No Good For Tha Economy... Oh... The Economy...",
	"Sucking Feet Edition",
	"Stuck In 2024 Edition",
	"Version Where The Fake Versions Have More Effort Put Into Them Than The Actual Game",
	"Nostalgia Edition, Because Oh, Those Were Surely The Days",
	"You Will Kneel Down To Me While I Take Your Money Edition",
	"Hastily Compiled Edition",
	"25k Steam Hours Edition (Like I'm Even Gonna Keep That High of a Retention Rate)",
	"Sweaty Nerd Edition (The Good Kind of Sweaty)",
	"Sweaty Nerd Edition (The Bad Kind of Sweaty)",
	"NO Edition. You Get NOTHING!",
	"The Version Where Midgetsausage Rants About Not Being Frontpaged In The Art Portal",
	"Not Fit For Consumption Edition",
	"Charliest Charlie Edition (It's TWICE the Charlie per Charlie!)",
	"Charliest Charlie Edition (That's 65% More Charlie per Charlie!)",
	"Charlie's Finest Hour Edition",
	"Charlie's Greatest Hits Edition",
	"Free and Open Source Edition",
	"Democracy Manifest Edition",
	"Gay, Gay, and Even More Gay Edition",
	"SNAFU Edition (Oh Lawd, Believe Me!)",
	"Spawncamped Edition",
	"Rush Hour Edition",
	"Free To Open, Pay To Play Edition",
	"Catastrophic Anisotropic Filtering Edition",
	
	# Misc jokes
	"& Knuckles",
	"Sponsored by Newgrounds! (They actually don't, but we're trying to get them to)",
	"You have not installed Charlie-Strike: Source",
	"I'm pretty sure this copy is pirated",
	"Now with 10% more AWoT per AWoT!",
	"if else if else if else if else if else",
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"delete system32",
	"vivziepop",
	"Lawyers LOVE this game!",
	"what",
	"You know none of the editions that show up here are real, right?",
	"Node graph out of date. Rebuilding...",
	"unbind all; bind w +forward; bind mouse1 +attack; bind s quit",
	"You're not actually supposed to access this game as it's been seized by the Central Intelligence Agency",
	"\"I acquired a copy of this software legally!\" yea we know u pirate but calm down we aint snitchin",
	"char_die",
	"#Mainmenu_fakeversion5",
	""]

func get_random() -> String:
	return list[randi() % list.size()]
